### PR TITLE
Updated to use CUDA7

### LINKED ISSUE #4: Upgrade to CUDA 7.0
```
sudo wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb 
sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb  
```

### PR DESCRIPTION
**Pull request by cancan101**
Closes #4

### CODE REVIEW

**Comment by ogrisel** [comment]
This looks good to me. Have you tested it on a new vanilla ubuntu instance?

At the end of the execution of the script you should reboot the instance and then you can run the `nvidia-smi` to check that CUDA is properly installed.

**Comment by cancan101** [comment]
@ogrisel Does installing `gfortran` belong in this script? I feel that should be installed in the script that installs scipy.

**Comment by cancan101** [comment]
Tested and this works.

**Comment by ogrisel** [comment]
Merging. Thanks. I agree for gfortran, feel free to do in another PR.

**Pull request merged**
